[package]
name = "babyjubjub-rs"
version = "0.1.0"
authors = ["arnaucube <arnaucube@gmail.com>"]
edition = "2018"

[dependencies]
num = "0.2.0"
num-bigint = {version = "0.2.2", features = ["rand"]}
num-traits = "0.2.8"
